### ISSUE TITLE
post params don't appear in Request until handleFileUploads is invoked.

### ISSUE THREAD

**Issue by creswick** [snapframework/snap-core#206]
I found this confusing and unintuitive, but I'm still not entirely sure it's actually broken.

Here's a small example:

``` haskell
{-# LANGUAGE OverloadedStrings #-}
module SimpleServer
  ( startServer
  )
  where

import           Control.Concurrent
import           Control.Monad.Trans     (liftIO)
import           Data.ByteString         ()
import           Data.Monoid
import           Data.Int (Int64)
import           Prelude hiding (log)
import           Snap.Core
import           Snap.Http.Server
import           Snap.Snaplet
import           Snap.Util.FileUploads
import           System.Directory (getTemporaryDirectory)

defaultMaxBodyLen :: Int64
defaultMaxBodyLen = 10000000

config :: Int -> Config Snap a
config port = setPort port mempty

startServer :: IO ThreadId
startServer = do
  (_, snap, _) <- runSnaplet (Just "Mock Server") testSnaplet
  threadId <- forkIO (simpleHttpServe (config 8080) snap)
  return threadId


testSnaplet :: SnapletInit () ()
testSnaplet = makeSnaplet "Mock Snaplet" "A handler for all requests" Nothing $ do
  wrapSite sendTo
  return ()

  where
    sendTo :: Handler () () () -> Handler () () ()
    sendTo _ = do
      tmpDir <- liftIO getTemporaryDirectory
      -- uncomment this to get post params to show up:
      -- handleFileUploads
      --   tmpDir
      --   defaultUploadPolicy
      --   (\_ -> allowWithMaximumSize defaultMaxBodyLen)
      --   (\_ -> return ())

      req <- getRequest
      log ("Got request: " ++ show req)
      finishWith (setResponseStatus 202 "Accepted" emptyResponse)


log :: String -> Handler () () ()
log str = liftIO $ putStrLn ("Mock Server: "++str)
```

Running `startServer` will start up a server on localhost:8080 that simply prints every request.

Sending a multipart/form-data POST request (eg. via curl: `curl --form postParam=1234 http://localhost:8080`) will print the request, but no params will be shown:

```
Mock Server: Got request: Request <
    server-name: localhost
    remote: 127.0.0.1:64863
    local: 127.0.0.1:8080
    Headers:
      ========================================
          Content-Length: 148
 User-Agent: curl/7.30.0
 Host: localhost:8080
 Accept: */*
 Content-Type: multipart/form-data; boundary=----------------------------4220d740dcd2
 Expect: 100-continue
      ========================================
    content-length: Just 148
    method: POST
    version: (1,1)
    cookies:
      ========================================

      ========================================
    pathinfo:
    contextpath: /
    URI: /
    params:
      ========================================

      ========================================
>
```

Uncomment the handleFileUploads invocation (make sure to get all 5 lines), and try again:

```
Mock Server: Got request: Request <
    server-name: localhost
    remote: 127.0.0.1:64867
    local: 127.0.0.1:8080
    Headers:
      ========================================
          Content-Length: 148
 User-Agent: curl/7.30.0
 Host: localhost:8080
 Accept: */*
 Content-Type: multipart/form-data; boundary=----------------------------2aaf16e8f1f8
 Expect: 100-continue
      ========================================
    content-length: Just 148
    method: POST
    version: (1,1)
    cookies:
      ========================================

      ========================================
    pathinfo:
    contextpath: /
    URI: /
    params:
      ========================================
      postParam: ["1234"]
      ========================================
>
```

Notice that `postParam` is now listed with its value.

This does not seem to be an issue with application/x-www-form-urlencoded POST requests (as you get when using curl's --data flag).
