### ISSUE TITLE
Failed test suite on Stackage build server

### ISSUE THREAD

**Issue by snoyberg** [snapframework/snap-core#261]
Unfortunately I don't have more information than this:

```
Snap.Util.FileServe.Tests:
  fileServe/foo.bin: [OK]
  fileServe/foo.txt: [OK]
  fileServe/foo.html: [OK]
  fileServe/foo.bin.bin.bin: [OK]
  fileServe/directory-passes: [OK]
  fileServe/404s: [OK]
  fileServe/Single: [OK]
  fileServe/cfgA: [OK]
  fileServe/cfgB: [OK]
  fileServe/cfgC: [OK]
  fileServe/cfgD: [OK]
  fileServe/cfgFancy: [Failed]
```
